import { formatYear, type Year } from './time'

/**
 * Historical polities as time-varying border polygons.
 *
 * DATA (src/data/nations.json), one object per polity:
 *
 *   id            stable key
 *   name          display name
 *   color         six-digit hex; the globe layer appends an alpha to it
 *   from, to      existence span (astronomical years, 1 BCE = 0)
 *   visibleFrom,  the *notability* window — when this polity is worth drawing.
 *   visibleTo     Independent of existence: the Abbasids lasted to 1258 but stop
 *                 being one of the world's headline powers around 1000, and Kush
 *                 only becomes interesting a couple of centuries after it forms.
 *                 The windows are curated so that any instant shows 3-8 polities.
 *   keyframes     [{ time, rings }] sorted by time. `rings` is a list of open
 *                 rings in GeoJSON [lng, lat] order — several per keyframe when a
 *                 polity is not one connected blob (islands, or Britain + India).
 *
 * Borders hold: the keyframe in force at t is the last one at or before t, and
 * the first keyframe also holds *backwards* to the start of existence, so a
 * polity is never drawn borderless during its own lifetime.
 *
 * The rings were generated by intersecting hand-drawn extent polygons with real
 * coastlines (Natural Earth 50m land) and simplifying — which is why they hug
 * the coast but keep inland frontiers deliberately smooth and approximate.
 * Lakes are not cut out: a ring may cross the Caspian.
 */

/**
 * Ring in GeoJSON order: [lng, lat]. Left open — the renderer closes it.
 *
 * Wound CLOCKWISE (negative shoelace). On a sphere a ring encloses two regions,
 * and the globe's polygon layer fills the one clockwise winding bounds; a
 * counter-clockwise ring paints the whole planet *except* the nation, which is
 * exactly how the previous dataset managed to look so wrong.
 */
export type Ring = [number, number][]

export interface NationKeyframe {
  time: Year
  rings: Ring[]
}

export interface Nation {
  id: string
  name: string
  color: string // hex like '#b05c4a'
  from: Year
  to: Year
  visibleFrom: Year
  visibleTo: Year
  keyframes: NationKeyframe[]
}

/** Hard ceiling on simultaneous polities; the data aims well below it. */
export const MAX_VISIBLE = 10

/** True while the polity exists *and* is one of the period's notable powers. */
export const isNotable = (n: Nation, t: Year): boolean =>
  t >= n.from && t <= n.to && t >= n.visibleFrom && t <= n.visibleTo

/** Borders in force at t (hold-first, hold-last), or undefined outside existence. */
export function activeKeyframe(n: Nation, t: Year): NationKeyframe | undefined {
  if (t < n.from || t > n.to || !n.keyframes.length) return undefined
  let cur = n.keyframes[0]
  for (const k of n.keyframes) {
    if (k.time > t) break
    cur = k
  }
  return cur
}

/** Planar shoelace, signed: negative means clockwise, the winding the renderer fills. */
export const signedRingArea = (ring: Ring): number =>
  ring.reduce((sum, [x, y], i) => {
    const [nx, ny] = ring[(i + 1) % ring.length]
    return sum + x * ny - nx * y
  }, 0) / 2

/** Planar shoelace area — an approximation, used only to rank extents. */
export const ringArea = (ring: Ring): number => Math.abs(signedRingArea(ring))

export const keyframeArea = (k: NationKeyframe): number =>
  k.rings.reduce((sum, r) => sum + ringArea(r), 0)

/**
 * The polities to draw at t: notable ones, largest first, capped. The cap is a
 * backstop for bad data — curation is what actually keeps the globe legible.
 */
export function visibleNations(nations: Nation[], t: Year, limit = MAX_VISIBLE): Nation[] {
  return nations
    .filter((n) => isNotable(n, t) && activeKeyframe(n, t))
    .sort((a, b) => keyframeArea(activeKeyframe(b, t)!) - keyframeArea(activeKeyframe(a, t)!))
    .slice(0, limit)
}

/** "Roman Empire (509 BCE – 476)" — polygon labels carry the span, not the keyframe. */
export const nationLabel = (n: Nation): string =>
  `${n.name} (${formatYear(n.from)} – ${formatYear(n.to)})`


