import type { TextureKeyframe } from '../lib/paleo'
import frames from './paleoFrames.json'

export const MODERN_TEXTURE = '//unpkg.com/three-globe/example/img/earth-blue-marble.jpg'
export const NIGHT_TEXTURE = '//unpkg.com/three-globe/example/img/earth-night.jpg'

const base = import.meta.env.BASE_URL // app may be served from a sub-path (GitHub Pages)

/**
 * Globe texture timeline: ~30 plate-drift frames generated by
 * scripts/gen_paleo_v3.py (rigid plate transforms interpolated from Pangaea to
 * the modern layout), then the real modern map pinned from ~10 ka so nothing
 * morphs within the most recent 10,000 years. Refine geography by editing the
 * plate shapes/transforms in the generator and re-running it.
 */
export const PALEO_FRAMES: TextureKeyframe[] = [
  ...frames.map((f) => ({ time: f.time, url: `${base}textures/paleo/${f.file}` })),
  { time: -10_000, url: MODERN_TEXTURE },
]
