import type { TextureKeyframe } from '../lib/paleo'
import frames from './paleoFrames.json'

const base = import.meta.env.BASE_URL // app may be served from a sub-path (GitHub Pages)

// Base maps are bundled (public/textures/base) so first paint never depends on
// a third-party CDN; sharper sources may still upgrade them after load.
export const MODERN_TEXTURE = `${base}textures/base/earth-blue-marble.jpg`
export const NIGHT_TEXTURE = `${base}textures/base/earth-night.jpg`
export const RELIEF_TEXTURE = `${base}textures/base/earth-topology.png`
export const SKY_TEXTURE = `${base}textures/base/night-sky.png`

/**
 * Globe texture timeline: ~30 plate-drift frames generated by
 * scripts/gen_paleo_v3.py (rigid plate transforms interpolated from Pangaea to
 * the modern layout), then the real modern map pinned from ~10 ka so nothing
 * morphs within the most recent 10,000 years. Refine geography by editing the
 * plate shapes/transforms in the generator and re-running it.
 */
export const PALEO_FRAMES: TextureKeyframe[] = [
  ...frames.map((f) => ({ time: f.time, url: `${base}textures/paleo/${f.file}` })),
  { time: -10_000, url: MODERN_TEXTURE },
]
